
web:
  build: ..
  ports:
    - "8000:8000"
  environment:
    - DJANGO_DEBUG=True
    - DJANGO_DATABASE_NAME=database
    - DJANGO_DATABASE_USER=postgres
    - DJANGO_DATABASE_PASSWORD=
    - DJANGO_DATABASE_HOST=postgres
    - DJANGO_DATABASE_PORT=5432
    - DJANGO_SECRET=<Django Secret>
    - DJANGO_EMAIL_USE_TLS=True
    - DJANGO_EMAIL_HOST=
    - DJANGO_EMAIL_HOST_USER=
    - DJANGO_EMAIL_HOST_PASSWORD=
    - DJANGO_EMAIL_PORT=587
  volumes:
    - ../src/:/app
  external_links:
    - postgresql:postgres
  command: python manage.py runserver 0.0.0.0:8000
